### PR TITLE
fix: debug logs written to stderr

### PR DESCRIPTION
**Pull request by jnorkus**
https://github.com/pelias/logger/issues/60

### CODE REVIEW

**Comment by missinglink** [comment]
heya, just wondering if we should set these other levels <3?

```
  emerg: 0,
  alert: 1,
  crit: 2,
  error: 3,
  
  ----
  
  warning: 4,
  notice: 5,
  info: 6,
  debug: 7
```

**Comment by jnorkus** [comment]
> heya, just wondering if we should set these other levels <3?
> 
> ```
>   emerg: 0,
>   alert: 1,
>   crit: 2,
>   error: 3,
>   
>   ----
>   
>   warning: 4,
>   notice: 5,
>   info: 6,
>   debug: 7
> ```

Makes sense. Updated.

**Comment by missinglink** [comment]
yeah I agree conceptually that this is preferable, we adopted this convention from `winston`, where it's hotly debated:
https://github.com/winstonjs/winston/issues/927

**Comment by missinglink** [comment]
The CI is broken for outside contributors, I'll have to pull your commits into a branch on this org to get the tests passing, I'll then merge that PR which will link to and close this one.

**Comment by missinglink** [comment]
@jnorkus did you test this and confirm it works as expected?

**Comment by jnorkus** [comment]
> @jnorkus did you test this and confirm it works as expected?

I have not tested the latest change where I added the suggested levels but I have the previous one (error only) running in production on a patched container.

**Comment by missinglink** [comment]
Right fair enough, I assume that if adding `emerg`, `crit` etc... caused a fatal error at runtime then we'd see some test failures, which we don't, so looks good to me.

**Comment by missinglink** [comment]
https://github.com/pelias/logger/releases/tag/v1.6.0

thanks @jnorkus

**Pull request closed without merging**
